/**
 * Testi VDT / NON VDT per template unico (placeholder {{NOME}}).
 * Sorgente: fields-map.md §3 + testo completo da Modulo Illuminamento VDT / NON VDT 2022.docx
 */
(function () {
  'use strict';

  const ASSENZA_VDT =
    'Dall\'analisi del ciclo produttivo della società {{RAGIONE_SOCIALE}} si è rilevata l\'assenza di gruppi omogenei di lavoratori classificabili come videoterminalisti, in quanto se pur presenti sistemi informatici nella struttura, essi vengono utilizzati in modo sistematico o abituale per meno di 20 ore/settimana.';

  window.VDT_TEXT_BLOCKS = [
    {
      id: 'titolo_modulo',
      placeholder: 'TITOLO_MODULO',
      label: 'Titolo modulo (copertina)',
      sezione: 'Copertina',
      vdt: 'Analisi delle postazioni munite di videoterminale e dei livelli di illuminamento',
      nonVdt: 'Analisi dei livelli di illuminamento delle postazioni di lavoro',
    },
    {
      id: 'titolo_cap2',
      placeholder: 'TITOLO_CAP2',
      label: 'Titolo cap. 2',
      sezione: 'Cap. 2',
      vdt: 'ILLUMINAMENTO E VIDEOTERMINALI',
      nonVdt: 'ILLUMINAMENTO',
    },
    {
      id: 'premessa_indagini',
      placeholder: 'PREMESSA_INDAGINI',
      label: 'Premessa — frase indagini',
      sezione: '§1 Premessa',
      vdt: 'indagini sull\'ergonomia delle postazioni al videoterminale e sui livelli di illuminamento',
      nonVdt: 'indagini sull\'ergonomia delle postazioni di lavoro (comprensive anche di videoterminali) e sui livelli di illuminamento',
    },
    {
      id: 'premessa_nota_assenza',
      placeholder: 'PREMESSA_NOTA_ASSENZA',
      label: 'Premessa — nota assenza VDT',
      sezione: '§1 Premessa',
      vdt: '',
      nonVdt: ASSENZA_VDT,
      onlyNonVdt: true,
    },
    {
      id: 'premessa_pertanto',
      placeholder: 'PREMESSA_PERTANTO',
      label: 'Premessa — paragrafo «Pertanto…»',
      sezione: '§1 Premessa',
      vdt: '',
      nonVdt: 'Pertanto, la presente analisi risulta fondamentale al fine di stabilire i parametri minimi dell\'illuminazione, anche in relazione alla tipologia di attività svolta.',
      onlyNonVdt: true,
    },
    {
      id: 'cap2_intro',
      placeholder: 'CAP2_INTRO',
      label: '§2.1 Introduzione cap. 2',
      sezione: '§2.1',
      vdt: [
        'La figura del videoterminalista ben si distingue da quella del semplice impiegato che solo sporadicamente fa uso del videoterminale. Con l\'entrata in vigore del D.Lgs. 81/08, l\'Italia si è allineata con la Legge Comunitaria 2000 (L. ) alle disposizioni delle UE in relazione alla tutela della salute e della sicurezza nel lavoro al videoterminale. Le novità principali sono due e riguardano la definizione di «videoterminalista» e la «periodicità» delle visite mediche.',
        'La definizione di videoterminalista, così come riveduta e corretta dalla citata norma, stabilisce che è tale quel lavoratore che utilizza un\'attrezzatura munita di videoterminale, in modo sistematico e abituale «per venti ore settimanali». La definizione comprende anche i sistemi denominati portatili. Si ricorda che la precedente definizione recitava «per almeno quattro ore consecutive giornaliere per tutta la settimana lavorativa».',
        'Si ricorda inoltre che le visite periodiche di controllo oftalmologico devono essere effettuate, salvo differente parere del Medico Competente, almeno ogni n° 5 anni e saranno biennali per i lavoratori che hanno superato i 50 anni di età.',
        'Tali aspetti sono stati sostanzialmente ripresi dal D.Lgs. 81/08.',
      ].join('\n\n'),
      nonVdt: [
        'Il D.Lgs. 81/08 prevede che gli ambienti di lavoro siano correttamente illuminati ed in particolare per gli ambienti di lavoro indoor sono previste le seguenti disposizioni riportate in allegato IV del Testo Unico:',
        'A meno che non sia richiesto diversamente dalle necessità delle lavorazioni e salvo che non si tratti di locali sotterranei, i luoghi di lavoro devono disporre di sufficiente luce naturale. In ogni caso, tutti i predetti locali e luoghi di lavoro devono essere dotati di dispositivi che consentano un\'illuminazione artificiale adeguata per salvaguardare la sicurezza, la salute e il benessere di lavoratori.',
        'Gli impianti di illuminazione dei locali di lavoro e delle vie di circolazione devono essere installati in modo che il tipo d\'illuminazione previsto non rappresenti un rischio di infortunio per i lavoratori.',
        'I luoghi di lavoro nei quali i lavoratori sono particolarmente esposti a rischi in caso di guasto dell\'illuminazione artificiale, devono disporre di un\'illuminazione di sicurezza di sufficiente intensità.',
        'Le superfici vetrate illuminanti ed i mezzi di illuminazione artificiale devono essere tenuti costantemente in buone condizioni di pulizia e di efficienza.',
        'Gli ambienti, i posti di lavoro ed i passaggi devono essere illuminati con luce naturale o artificiale in modo da assicurare una sufficiente visibilità.',
        'Nei casi in cui, per le esigenze tecniche di particolari lavorazioni o procedimenti, non sia possibile illuminare adeguatamente gli ambienti si devono adottare adeguate misure dirette ad eliminare i rischi derivanti dalla mancanza e dalla insufficienza della illuminazione.',
      ].join('\n\n'),
    },
    {
      id: 'cap2_ponte_normativo',
      placeholder: 'CAP2_PONTE_NORMATIVO',
      label: '§2.1 Ponte verso norma UNI (solo VDT)',
      sezione: '§2.1',
      vdt: 'Prima di passare agli elementi tecnici utili, e cioè alla regolamentazione ergonomica vera e propria, sono opportuni alcuni richiami di carattere generale riguardanti l\'illuminazione e la visualizzazione.',
      nonVdt: '',
      onlyVdt: true,
    },
    {
      id: 'ergonomia_23_intro',
      placeholder: 'ERGONOMIA_23_INTRO',
      label: '§2.3 Intro assenza VDT (solo NON VDT)',
      sezione: '§2.3',
      vdt: '',
      nonVdt: [
        ASSENZA_VDT,
        'Tuttavia, al fine di rendere la postazione di lavoro ergonomicamente idonea, si farà riferimento a quanto di seguito riportato al fine di determinare le condizioni operative tali da assicurare sicurezza e confort adeguati al lavoro svolto.',
      ].join('\n\n'),
      onlyNonVdt: true,
    },
    {
      id: 'titolo_sez_24',
      placeholder: 'TITOLO_SEZ_24',
      label: '§2.4 Titolo sezione',
      sezione: '§2.4',
      vdt: 'Igiene del lavoro al videoterminale',
      nonVdt: 'Igiene del lavoro',
    },
    {
      id: 'sez_24_nota',
      placeholder: 'SEZ_24_NOTA_FINALE',
      label: '§2.4 Nota finale (solo NON VDT)',
      sezione: '§2.4',
      vdt: '',
      nonVdt: 'Si ricorda come dall\'analisi del ciclo produttivo della società {{RAGIONE_SOCIALE}} si è rilevata l\'assenza di gruppi omogenei di lavoratori classificabili come videoterminalisti, in quanto se pur presenti sistemi informatici nella struttura, essi vengono utilizzati in modo sistematico o abituale per meno di 20 ore/settimana.',
      onlyNonVdt: true,
    },
    {
      id: 'misura_premessa',
      placeholder: 'MISURA_PREMESSA_VDT',
      label: '§3.1 Premessa misura — riferimento VDT',
      sezione: '§3.1',
      vdt: 'durante lo svolgimento del lavoro al videoterminale',
      nonVdt: 'durante lo svolgimento delle attività lavorative',
    },
    {
      id: 'metodiche_indirizzo',
      placeholder: 'METODICHE_INDIRIZZO_POSTAZIONI',
      label: '§3.3 Metodiche — oggetto indagine',
      sezione: '§3.3',
      vdt: 'postazioni munite di VDT',
      nonVdt: 'postazioni di lavoro',
    },
    {
      id: 'testo_lampade',
      placeholder: 'TESTO_LAMPADE_ILLUMINAZIONE',
      label: '§3.5.1 / locali — tipo lampade',
      sezione: '§3.5.1',
      vdt: 'lampade al neon / LED e lampade da tavolo',
      nonVdt: 'lampade al neon e lampade da tavolo',
    },
    {
      id: 'titolo_352',
      placeholder: 'TITOLO_352',
      label: '§3.5.2 Titolo risultati misure',
      sezione: '§3.5.2',
      vdt: 'Risultati delle misure per le postazioni videoterminali',
      nonVdt: 'Risultati delle misure per le postazioni DI LAVORO',
    },
    {
      id: 'intro_352',
      placeholder: 'INTRO_352',
      label: '§3.5.2 Intro tabella misure',
      sezione: '§3.5.2',
      vdt: 'I risultati diretti per le misure di illuminamento per le postazioni videoterminali sono riportati nella tabella 1.',
      nonVdt: 'I risultati diretti per le misure di illuminamento per le postazioni di lavoro sono riportati nella tabella 1.',
    },
    {
      id: 'bullet_lux',
      placeholder: 'BULLET_RAPPORTI_LUX',
      label: '§3.5.2 Elenco — rapporti lux',
      sezione: '§3.5.2',
      vdt: 'rapporti tra i livelli di illuminamento non ottimali (lux tastiera/lux ambiente<);',
      nonVdt: 'rapporti tra i livelli di illuminamento non ottimali;',
    },
    {
      id: 'bullet_riflessi',
      placeholder: 'BULLET_RIFLESSI',
      label: '§3.5.2 Elenco — riflessi',
      sezione: '§3.5.2',
      vdt: 'presenza di riflessi sullo schermo;',
      nonVdt: 'presenza di riflessi sullo schermo/postazione;',
    },
    {
      id: 'conclusioni_p1',
      placeholder: 'CONCLUSIONI_P1',
      label: '§4 Conclusioni — primo paragrafo',
      sezione: '§4',
      vdt: 'Dall\'analisi condotta sulle postazioni al VDT della sede di {{SEDE_OPERATIVA}} della {{RAGIONE_SOCIALE}} è emerso che all\'interno degli uffici il livello di illuminamento è conforme a quanto previsto dalla normativa per le attività di tipo ufficio; solo in casi puntuali si sono registrati dei minimi scostamenti dai livelli ottimali di comfort, da riferirsi talvolta alle condizioni al contorno (livello di illuminamento), all\'utilizzo di computer portatili ed all\'ergonomia del posto di lavoro.',
      nonVdt: 'Dall\'analisi condotta sulle postazioni di lavoro della sede di {{SEDE_OPERATIVA}} della {{RAGIONE_SOCIALE}} si può quindi affermare che i valori misurati risultano essere conformi ai range consigliati dalla norma UNI EN 12464-1, per le attività svolte e per la destinazione d\'uso dei locali presenti. Solo in casi puntuali si sono registrati dei minimi scostamenti dai livelli ottimali di comfort, da riferirsi talvolta alle condizioni al contorno (livello di illuminamento), all\'ergonomia del posto di lavoro o alla disposizione dei sistemi di illuminamento.',
    },
    {
      id: 'conclusioni_monitor',
      placeholder: 'CONCLUSIONI_MONITOR',
      label: '§4 Conclusioni — monitor / portatili',
      sezione: '§4',
      vdt: 'La maggior parte delle postazioni prevede l\'utilizzo di personal computer portatili, e per gestire al meglio questa caratteristica vengono forniti sistemi per la regolazione dell\'altezza e dell\'inclinazione dello schermo, nonché tastiere ausiliarie da utilizzare al posto di quelle dei laptop in modo da evitare condizioni di discomfort generate dall\'utilizzo prolungato degli stessi.',
      nonVdt: 'La maggior parte delle postazioni prevede l\'utilizzo di personal computer portatili, e per gestire al meglio questa caratteristica vengono forniti sistemi per la regolazione dell\'altezza e dell\'inclinazione dello schermo, nonché tastiere ausiliarie da utilizzare al posto di quelle dei laptop in modo da evitare condizioni di discomfort generate dall\'utilizzo prolungato degli stessi (si ricorda l\'assenza di gruppi omogenei di lavoratori classificabili come videoterminalisti).',
    },
    {
      id: 'conclusioni_registro',
      placeholder: 'CONCLUSIONI_REGISTRO_MANUTENZIONE',
      label: '§4 Registro manutenzione monitor',
      sezione: '§4',
      vdt: 'Relativamente ad eventuali problemi di nitidezza dei caratteri degli schermi dei VDT, si suggerisce di sottoporre periodicamente gli stessi a taratura e di istituire un «Registro di manutenzione» dove vengono riportati gli schermi sui quali è stata effettuata la manutenzione ed eventualmente richieste da parte del personale nei confronti del tecnico.',
      nonVdt: '',
      onlyVdt: true,
    },
    {
      id: 'conclusioni_responsabile',
      placeholder: 'CONCLUSIONI_RESPONSABILE',
      label: '§4 Responsabile postazioni',
      sezione: '§4',
      vdt: 'Da un punto di vista gestionale, si consiglia di nominare un "Responsabile per la postazione, l\'installazione ed il controllo dei posti di lavoro al VDT", il quale dovrà controllare periodicamente i posti di lavoro al VDT circa eventuali modifiche inadeguate da parte dell\'utente, consultando anche il RSPP.',
      nonVdt: 'Da un punto di vista gestionale, si consiglia di nominare un "Responsabile per la postazione, l\'installazione ed il controllo dei posti di lavoro", il quale dovrà controllare periodicamente gli stessi circa eventuali modifiche inadeguate da parte dell\'utente/operatore che possano inficiare l\'ergonomia e le caratteristiche di illuminamento, consultando anche il RSPP.',
    },
    {
      id: 'conclusioni_illuminamento_finale',
      placeholder: 'CONCLUSIONI_ILLUMINAMENTO_FINALE',
      label: '§4 Chiusura illuminamento postazioni',
      sezione: '§4',
      vdt: 'In merito ai risultati ottenuti nella misura dell\'illuminamento sulle diverse postazioni VDT si può affermare che il livello di illuminamento sulle postazioni di lavoro è adeguato.',
      nonVdt: 'In merito ai risultati ottenuti nella misura dell\'illuminamento sulle diverse postazioni si può affermare che il livello di illuminamento sulle postazioni di lavoro è adeguato.',
    },
    {
      id: 'conclusioni_indagine_vdt',
      placeholder: 'CONCLUSIONI_NOTA_VDT',
      label: '§4 Nota assenza VDT in indagine',
      sezione: '§4',
      vdt: '',
      nonVdt: 'L\'indagine strumentale ha permesso di constatare che i livelli di illuminamento sono adeguati anche in relazione al particolare tipo di attività svolta (si ricorda l\'assenza di gruppi omogenei di lavoratori classificabili come videoterminalisti).',
      onlyNonVdt: true,
    },
  ];

  /** Per anteprima Compila (pannello varianti) */
  window.VDT_VARIANTS = window.VDT_TEXT_BLOCKS.map((b) => ({
    id: b.id,
    label: b.label,
    sezione: b.sezione,
    vdt: b.onlyNonVdt ? '(non applicabile — solo NON VDT)' : (b.vdt || '(vuoto)'),
    nonVdt: b.onlyVdt ? '(non applicabile — solo VDT)' : (b.nonVdt || '(vuoto)'),
    onlyNonVdt: !!b.onlyNonVdt,
    onlyVdt: !!b.onlyVdt,
    placeholder: b.placeholder,
  }));
})();
